logging_sinks:
  honeycomb:
    type: honeycomb
    inputs:
      - k8s_logs
    api_key: ${HONEYCOMB_API_KEY:?err}
    dataset: k8s

### PREREQUESITE: create a kubernetes secret via
### kubectl create secret generic honeycomb-credentials --namespace vector --from-literal=HONEYCOMB_API_KEY=<YOUR_HONEYCOMB_API_KEY>
env:
  honeycomb:
    - name: HONEYCOMB_API_KEY
      valueFrom:
        secretKeyRef:
          name: honeycomb-credentials
          key: HONEYCOMB_API_KEY
