# This provides a values example for a humio sink with some recommended settings.
# For docs on availabe config options check https://vector.dev/docs/reference/configuration/sinks/humio_logs/ .
# The TLDR is:
# most defaults are fine as baseline config.
# - set compression: gzip. Typically this will save you 90-95% in Network Egress at the cost of some (negligible amount) of CPU to handle the compression.
# - set rate_limit_num: 100 or something higher than the default. The default is `10` which is a bit too conservative and can easily lead backpressure for high-volume sources.
logging_sinks:
  humio:
    type: humio_logs
    inputs:
      - k8s_logs
    token: ${HUMIO_TOKEN:?err}
    endpoint: https://cloud.community.humio.com
    encoding:
      codec: json
    compression: gzip
    request:
      rate_limit_num: 100

### PREREQUESITE: create a kubernetes secret via
### kubectl create secret generic humio-token --namespace vector --from-literal=HUMIO_TOKEN=<YOUR_HUMIO_INGEST_TOKEN>
env:
  humio:
    - name: HUMIO_TOKEN
      valueFrom:
        secretKeyRef:
          name: humio-token
          key: HUMIO_TOKEN
