logging_sinks:
  observe:
    type: http
    inputs:
      - k8s_logs
    uri: https://collect.observeinc.com/v1/http
    compression: gzip
    auth:
      strategy: basic
      user: ${OBSERVE_CUSTOMER_ID:?err}
      password: ${OBSERVE_TOKEN:?err}
    encoding:
      codec: json

### PREREQUESITE: create a kubernetes secret via
### kubectl create secret generic observe-credentials --namespace vector --from-literal=OBSERVE_CUSTOMER_ID=<YOUR_OBSERVE_CUSTOMER_ID> --from-literal=OBSERVE_TOKEN=<OBSERVE_TOKEN>
env:
  observe:
    - name: OBSERVE_CUSTOMER_ID
      valueFrom:
        secretKeyRef:
          name: observe-credentials
          key: OBSERVE_CUSTOMER_ID
    - name: OBSERVE_TOKEN
      valueFrom:
        secretKeyRef:
          name: observe-credentials
          key: OBSERVE_TOKEN
