[package]
name = "mvhashmap"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Move hash map"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
crossbeam = "0.8.1"
dashmap = "5.2.0"

[dev-dependencies]
proptest = "1.0.0"
proptest-derive = "0.3.0"
rayon = "1.5.2"
