
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aptos-indexer.fullname" . }}
  labels:
    {{- include "aptos-indexer.labels" . | nindent 4 }}
    app.kubernetes.io/name: indexer
spec:
  selector:
    matchLabels:
      {{- include "aptos-indexer.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/name: indexer
  template:
    metadata:
      labels:
        {{- include "aptos-indexer.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/name: indexer
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
    spec:
      containers:
      - name: indexer
        resources:
          {{- toYaml .Values.indexer.resources | nindent 10 }}
        env:
        - name: RUST_BACKTRACE
          value: "1"
        - name: DATABASE_URI
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-credentials
              key: pg_db_uri
        image: {{ .Values.indexer.image.repo }}:{{ .Values.indexer.image.tag }}
        imagePullPolicy: {{ .Values.indexer.image.pullPolicy }}
        command:
          - sh
          - -c
          - |
            aptos-indexer --pg-uri=$DATABASE_URI --node-url={{ .Values.nodeUrl }} \
              {{- if .Values.indexTokenData }}
              --index-token-data \
              {{- end }}
              --emit-every {{ .Values.emitEvery }} \
              --batch-size {{ .Values.batchSize }}
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      securityContext:
        runAsNonRoot: true
        runAsUser: 6180
        runAsGroup: 6180
      serviceAccountName: {{ include "aptos-indexer.serviceAccountName" . }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "aptos-indexer.fullname" . }}
  labels:
    {{- include "aptos-indexer.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: indexer
  ports:
  - port: 80
    targetPort: 8080
  type: NodePort
  externalTrafficPolicy: Local
