{{- if .Values.indexer_server.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aptos-indexer.fullname" . }}-server
  labels:
    {{- include "aptos-indexer.labels" . | nindent 4 }}
    app.kubernetes.io/name: indexer-server
spec:
  selector:
    matchLabels:
      {{- include "aptos-indexer.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/name: indexer-server
  template:
    metadata:
      labels:
        {{- include "aptos-indexer.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/name: indexer-server
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
    spec:
      containers:
      - name: indexer-server
        resources:
          {{- toYaml .Values.indexer_server.resources | nindent 10 }}
        env:
        - name: RUST_BACKTRACE
          value: "1"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-credentials
              key: pg_db_uri
        image: {{ .Values.indexer_server.image.repo }}:{{ .Values.indexer_server.image.tag }}
        imagePullPolicy: {{ .Values.indexer_server.image.pullPolicy }}
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      securityContext:
        runAsNonRoot: true
        runAsUser: 6180
        runAsGroup: 6180
      serviceAccountName: {{ include "aptos-indexer.serviceAccountName" . }}
      volumes:
      - name: tmp
        emptyDir: {}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "aptos-indexer.fullname" . }}-server-lb
  labels:
    {{- include "aptos-indexer.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{- include "aptos-indexer.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/name: indexer-server
  ports:
  - name: api
    port: 80
    targetPort: 4000
  {{- with .Values.service }}
  type: {{ .type }}
  externalTrafficPolicy: {{ .externalTrafficPolicy }}
  loadBalancerSourceRanges:
    {{- toYaml .loadBalancerSourceRanges | nindent 4 }}
  {{- end }}

{{- end }}
