apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "aptos-indexer.fullname" . }}
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: runtime/default
spec:
  privileged: false
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  requiredDropCapabilities:
  - ALL
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: MustRunAsNonRoot
  runAsGroup:
    rule: MustRunAs
    ranges:
    - min: 1
      max: 65535
  supplementalGroups:
    rule: MayRunAs
    ranges:
    - min: 1
      max: 65535
  fsGroup:
    rule: MayRunAs
    ranges:
    - min: 1
      max: 65535
  seLinux:
    rule: RunAsAny
  volumes:
  - configMap
  - emptyDir
  - projected
  - secret
  - downwardAPI
  - persistentVolumeClaim

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "aptos-indexer.fullname" . }}-psp
rules:
- apiGroups: ["policy"]
  resources: ["podsecuritypolicies"]
  verbs: ["use"]
  resourceNames:
  - {{ include "aptos-indexer.fullname" . }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "aptos-indexer.fullname" . }}-psp
roleRef:
  kind: ClusterRole
  name: {{ include "aptos-indexer.fullname" . }}-psp
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
  name: {{ include "aptos-indexer.serviceAccountName" . }}
