[package]
name = "aptos-api-test-context"
version = "0.2.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos API test context"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.57"
aptos-api = { path = "../", package = "aptos-api" }
aptos-api-types = { path = "../types", package = "aptos-api-types" }
aptos-config = { path = "../../config" }
aptos-crypto = { path = "../../crates/aptos-crypto" }
aptos-genesis = { path = "../../crates/aptos-genesis", features = ["testing"] }
aptos-global-constants = { path = "../../config/global-constants" }
aptos-logger = { path = "../../crates/aptos-logger" }
aptos-mempool = { path = "../../mempool", features = ["fuzzing"] }
aptos-metrics-core = { path = "../../crates/aptos-metrics-core" }
aptos-proptest-helpers = { path = "../../crates/aptos-proptest-helpers" }
aptos-sdk = { path = "../../sdk" }
aptos-secure-storage = { path = "../../secure/storage" }
aptos-state-view = { path = "../../storage/state-view" }
aptos-temppath = { path = "../../crates/aptos-temppath" }
aptos-types = { path = "../../types" }
aptos-vm = { path = "../../aptos-move/aptos-vm" }
aptosdb = { path = "../../storage/aptosdb", features = ["fuzzing"] }
async-trait = "0.1.53"
bcs = "0.1.3"
bytes = "1.1.0"
cached-packages = { path = "../../aptos-move/framework/cached-packages" }
executor = { path = "../../execution/executor" }
executor-types = { path = "../../execution/executor-types" }
fail = "0.5.0"
framework = { path = "../../aptos-move/framework" }
futures = "0.3.21"
goldenfile = "1.1.0"
hex = "0.4.3"
hyper = "0.14.18"
mempool-notifications = { path = "../../state-sync/inter-component/mempool-notifications" }
mime = "0.3.16"
move-deps = { path = "../../aptos-move/move-deps" }
once_cell = "1.10.0"
paste = "1.0.7"
percent-encoding = "2.1.0"
poem = { git = "https://github.com/poem-web/poem", rev = "f39eba95cbfb52989e0eff516dad86719dc7dcba", features = ["anyhow", "rustls"] }
poem-openapi = { git = "https://github.com/poem-web/poem", rev = "f39eba95cbfb52989e0eff516dad86719dc7dcba", features = ["url"] }
proptest = { version = "1.0.0", default-features = true }
rand = "0.7.3"
regex = "1.5.5"
reqwest = { version = "0.11.10", features = ["blocking", "json"], default_features = false }
serde = { version = "1.0.137", features = ["derive"], default-features = false }
serde_json = { version = "1.0.81", features = ["preserve_order"] }
serde_path_to_error = "0.1"
storage-interface = { path = "../../storage/storage-interface" }
thiserror = "1.0.31"
tokio = { version = "1.18.2", features = ["full"] }
url = "2.2.2"
vm-validator = { path = "../../vm-validator" }
warp = { version = "0.3.2", features = ["default"] }
warp-reverse-proxy = "0.5.0"
