[package]
name = "aptos-node-checker"
version = "0.1.1"
description = "Aptos Node Health Checker"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
edition = "2018"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false

[dependencies]
anyhow = "1.0.57"
async-trait = "0.1.53"
clap = { version = "3.1.17", features = ["derive"] }
const_format = "0.2.26"
env_logger = "0.8.4"
futures = "0.3.21"
log = "0.4"
once_cell = "1.10.0"
poem = { git = "https://github.com/poem-web/poem", rev = "f39eba95cbfb52989e0eff516dad86719dc7dcba", features = ["anyhow"] }
poem-openapi = { git = "https://github.com/poem-web/poem", rev = "f39eba95cbfb52989e0eff516dad86719dc7dcba", features = ["swagger-ui", "url"] }
prometheus-parse = "0.2.2"
reqwest = "0.11.10"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
serde_yaml = "0.8.24"
thiserror = "1.0.31"
tokio = { version = "1.18.2", features = ["full"] }
url = { version = "2.2.2", features = ["serde"] }

aptos-api = { path = "../../api" }
aptos-config = { path = "../../config" }
aptos-crypto = { path = "../../crates/aptos-crypto" }
aptos-logger = { path = "../../crates/aptos-logger" }
aptos-rest-client = { path = "../../crates/aptos-rest-client" }
aptos-sdk = { path = "../../sdk" }

transaction-emitter-lib = { path = "../../crates/transaction-emitter-lib" }

[[bin]]
name = "aptos-node-checker"
