[package]
name = "aptos-bitvec"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos safe bitvec implementation"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
proptest = { version = "1.0.0", default-features = true, optional = true }
proptest-derive = { version = "0.3.0", optional = true }
serde = { version = "1.0.137", features = ["derive"] }
serde_bytes = "0.11.6"

[dev-dependencies]
bcs = "0.1.3"
proptest = { version = "1.0.0", default-features = true }
proptest-derive = { version = "0.3.0" }
serde_json = "1.0.83"

[features]
fuzzing = ["proptest-derive", "proptest"]
