[package]
name = "aptos"
version = "0.3.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos tool for management of nodes and interacting with the blockchain"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.57"
async-trait = "0.1.53"
base64 = "0.13.0"
bcs = "0.1.3"
clap = "3.2.11"
clap_complete = "3.2.3"
dirs = "4.0.0"
futures = "0.3.21"
hex = "0.4.3"
itertools = "0.10.3"
parse_duration = "2.1.1"
rand = "0.7.3"
regex = "1.1.5"
reqwest = { version = "0.11.10", features = ["blocking", "json"] }
serde = "1.0.137"
serde_bytes = "0.11.6"
serde_json = "1.0.81"
serde_yaml = "0.8.24"
shadow-rs = "0.16.2"
tempfile = "3.3.0"
termcolor = "1.1.3"
thiserror = "1.0.31"
tokio = { version = "1.18.2", features = ["full"] }
tokio-util = { version = "0.7.2", features = ["compat"] }
toml = "0.5.9"
uuid = { version = "1.0.0", features = ["v4", "serde"] }
walkdir = "2.3.2"

aptos-bitvec = { path = "../../crates/aptos-bitvec" }
aptos-config = { path = "../../config" }
aptos-crypto = { path = "../aptos-crypto", features = [] }
aptos-faucet = { path = "../aptos-faucet" }
aptos-gas = { path = "../../aptos-move/aptos-gas" }
aptos-genesis = { path = "../aptos-genesis" }
aptos-github-client = { path = "../../secure/storage/github" }
aptos-keygen = { path = "../aptos-keygen" }
aptos-logger = { path = "../aptos-logger" }
aptos-module-verifier = { path = "../../aptos-move/aptos-module-verifier" }
aptos-node = { path = "../../aptos-node" }
aptos-rest-client = { path = "../../crates/aptos-rest-client" }
aptos-sdk = { path = "../../sdk" }
aptos-secure-storage = { path = "../../secure/storage" }
aptos-telemetry = { path = "../aptos-telemetry" }
aptos-temppath = { path = "../aptos-temppath" }
aptos-transactional-test-harness = { path = "../../aptos-move/aptos-transactional-test-harness" }
aptos-types = { path = "../../types" }
aptos-vm = { path = "../../aptos-move/aptos-vm" }

aptosdb = { path = "../../storage/aptosdb" }
cached-packages = { path = '../../aptos-move/framework/cached-packages' }
executor = { path = "../../execution/executor" }
framework = { path = '../../aptos-move/framework' }
move-deps = { path = "../../aptos-move/move-deps", features = ["address32", "testing", "table-extension"] }
short-hex-str = { path = "../short-hex-str" }
storage-interface = { path = "../../storage/storage-interface" }
vm-genesis = { path = "../../aptos-move/vm-genesis" }

[features]
default = []
fuzzing = []

[build-dependencies]
shadow-rs = "0.16.2"
