[package]
name = "aptos-api-types"
version = "0.0.1"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos API Types"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.57"
async-trait = "0.1.53"
bcs = "0.1.3"
hex = "0.4.3"
indoc = "1.0.6"
mime = "0.3.16"
poem = { git = "https://github.com/poem-web/poem", rev = "f39eba95cbfb52989e0eff516dad86719dc7dcba" }
poem-openapi = { git = "https://github.com/poem-web/poem", rev = "f39eba95cbfb52989e0eff516dad86719dc7dcba" }
serde = { version = "1.0.137", default-features = false }
serde_json = "1.0.81"

aptos-config = { path = "../../config" }
aptos-crypto = { path = "../../crates/aptos-crypto" }
aptos-openapi = { path = "../../crates/aptos-openapi" }
aptos-state-view = { path = "../../storage/state-view" }
aptos-types = { path = "../../types" }
aptos-vm = { path = "../../aptos-move/aptos-vm" }

move-deps = { path = "../../aptos-move/move-deps", features = ["address32"] }
storage-interface = { path = "../../storage/storage-interface" }

[dev-dependencies]
move-deps = { path = "../../aptos-move/move-deps" }
