[package]
name = "generate-format"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos core type checker to ensure compatibility"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
bcs = "0.1.3"
rand = "0.7.3"
serde = { version = "1.0.137", features = ["derive"] }
serde-reflection = { git = "https://github.com/aptos-labs/serde-reflection", rev = "839aed62a20ddccf043c08961cfe74875741ccba" }
serde_yaml = "0.8.24"
structopt = "0.3.21"

aptos-config = { path = "../../config" }
aptos-crypto = { path = "../../crates/aptos-crypto", features = ["fuzzing"] }
aptos-crypto-derive = { path = "../../crates/aptos-crypto-derive" }
aptos-types = { path = "../../types", features = ["fuzzing"] }

consensus = { path = "../../consensus", features = ["fuzzing"] }
consensus-types = { path = "../../consensus/consensus-types", features = ["fuzzing"] }
move-deps = { path = "../../aptos-move/move-deps", features = ["address32", "fuzzing"] }
network = { path = "../../network" }

[[bin]]
name = "compute"
path = "src/compute.rs"
test = false
