base:
  role: "full_node"
  waypoint:
    from_file: "/opt/aptos/genesis/waypoint.txt"

execution:
  genesis_file_location: "/opt/aptos/genesis/genesis.blob"

full_node_networks:
- network_id: "public"
  discovery_method: "onchain"
  listen_address: "/ip4/0.0.0.0/tcp/6182"
  {{- if .Values.fullnode_identity }}
  identity:
    {{- .Values.fullnode_identity | toYaml | nindent 6 }}
  {{- end }}
  seeds:
    {{- (get .Values.aptos_chains .Values.chain.name).seeds | default dict | toYaml | nindent 6 }}
  {{- if .Values.fullnode_inbound_rate_limit }}
  inbound_rate_limit_config:
    {{- .Values.fullnode_inbound_rate_limit | toYaml | nindent 6 }}
  {{- end }}
  {{- if .Values.fullnode_outbound_rate_limit }}
  outbound_rate_limit_config:
    {{- .Values.fullnode_outbound_rate_limit | toYaml | nindent 6 }}
  {{- end }}
  max_inbound_connections: {{ .Values.fullnode_max_inbound_connections }}
storage:
  backup_service_address: "0.0.0.0:6186"
  storage_pruner_config:
    ledger_pruner_config:
      enable: {{ .Values.enable_ledger_pruner }}
      {{- if .Values.ledger_prune_window }}
      prune_window: {{ .Values.ledger_prune_window }}
      {{- end }}

state_sync:
  state_sync_driver:
    bootstrapping_mode: {{ .Values.bootstrapping_mode }}
    continuous_syncing_mode: {{ .Values.continuous_syncing_mode }}

api:
  address: "0.0.0.0:8080"
