[package]
name = "aptos-rosetta"
version = "0.0.1"
description = "Aptos Rosetta"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
edition = "2018"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false

[dependencies]
anyhow = "1.0.57"
aptos-config = { path = "../../config" }
aptos-crypto = { path = "../aptos-crypto" }
aptos-logger = { path = "../aptos-logger" }
aptos-metrics-core = { path = "../aptos-metrics-core" }
aptos-node = { path = "../../aptos-node" }
aptos-rest-client = { path = "../aptos-rest-client" }
aptos-sdk = { path = "../../sdk" }
aptos-types = { path = "../../types" }
aptos-warp-webserver = { path = "../aptos-warp-webserver" }
async-trait = "0.1.53"
bcs = "0.1.3"
cached-packages = { path = "../../aptos-move/framework/cached-packages" }
clap = "3.1.18"
futures = "0.3.17"
hex = "0.4.3"
itertools = "0.10.3"
percent-encoding = "2.1.0"
reqwest = { version = "0.11.10", features = ["json", "cookies"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
thiserror = "1.0.31"
tokio = { version = "1.18.2", features = ["full", "time"] }
url = "2.2.2"
warp = "0.3.2"

framework = { path = "../../aptos-move/framework" }
move-deps = { path = "../../aptos-move/move-deps" }
