[package]
name = "executor-types"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos executor interface types"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.57"
bcs = "0.1.3"
itertools = "0.10.0"
once_cell = "1.10.0"
serde = { version = "1.0.137", default-features = false }
thiserror = "1.0.31"

aptos-crypto = { path = "../../crates/aptos-crypto" }
aptos-secure-net = { path = "../../secure/net" }
aptos-state-view = { path = "../../storage/state-view" }
aptos-types = { path = "../../types" }

scratchpad = { path = "../../storage/scratchpad" }
storage-interface = { path = "../../storage/storage-interface" }

[features]
default = []
fuzzing = ["aptos-crypto/fuzzing", "aptos-types/fuzzing"]
