[package]
name = "aptos-github-client"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
repository = "https://github.com/aptos-labs/aptos-core"
description = "Aptos's Restful GitHub Client"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
serde = { version = "1.0.137", features = ["derive"], default-features = false }
serde_json = "1.0.81"
thiserror = "1.0.31"
ureq = { version = "1.5.4", features = ["json", "native-tls"], default-features = false }

proxy = { path = "../../../crates/proxy" }

[dev-dependencies]
base64 = "0.13.0"
