[package]
name = "netcore"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos netcore"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
bytes = "1.1.0"
futures = "0.3.21"
pin-project = "1.0.10"
serde = { version = "1.0.137", default-features = false }
tokio = { version = "1.18.2", features = ["full"] }
tokio-util = { version = "0.7.2", features = ["compat"] }
url = { version = "2.2.2" }

aptos-types = { path = "../../types" }

memsocket = { path = "../memsocket", optional = true }
proxy = { path = "../../crates/proxy" }

[dev-dependencies]
memsocket = { path = "../memsocket" }

[features]
default = []
fuzzing = ["memsocket/fuzzing", "aptos-types/fuzzing"]
testing = ["memsocket/testing"]
