[package]
name = "memsocket"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos memsocket"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
edition = "2018"
publish = false

[dependencies]
bytes = "1.1.0"
futures = "0.3.21"
once_cell = "1.10.0"

aptos-infallible = { path = "../../crates/aptos-infallible" }

[features]
default = []
fuzzing = []
testing = []
