[package]
name = "aptos-protos"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos Protobuf Definitions"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
bytes = "1.1.0"
pbjson = "0.4.0"
prost = "0.10.4"
serde = { version = "1.0.137", features = ["derive"], default-features = false }