version: "3.8"
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    volumes:
      - aptos-indexer-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-indexer}
    hostname: postgres.local
    networks:
      aptos-indexer:
        aliases:
          - postgres.local
    ports:
      - "5432:5432"
    expose:
      - 5432

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    volumes:
      - aptos-indexer-pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-aptos-indexer@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-indexer}
    hostname: pgadmin.local
    networks:
      aptos-indexer:
        aliases:
          - pgadmin.local
    ports:
      - "5050:80"
    expose:
      - 5050

  aptos-indexer:
    container_name: aptos-indexer
    image: aptoslabs/indexer:devnet
    depends_on:
      - postgres
    hostname: aptos-indexer.local
    networks:
      aptos-indexer:
        aliases:
          - aptos-indexer.local
    command: /usr/local/bin/aptos-indexer
      --pg-uri "postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres.local/${POSTGRES_DB:-indexer}"
      --node-url "${NODE_URL:-https://fullnode.devnet.aptoslabs.com}"
      --emit-every 25
      --batch-size 100

networks:
  aptos-indexer:
    name: aptos-indexer

volumes:
  aptos-indexer-db:
    name: aptos-indexer-db
  aptos-indexer-pgadmin:
    name: aptos-indexer-pgadmin
