[package]
name = "cached-packages"
version = "0.1.0"
edition = "2018"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Builds framework packages for caching in builds and tests"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false

[dependencies]
aptos-types = { path = "../../../types" }
bcs = "0.1.3"
framework = { path = ".." }
include_dir = { version = "0.7.2", features = ["glob"] }
move-deps = { path = "../../move-deps", features = ["address32"] }
once_cell = "1.10.0"
proptest = { version = "1.0.0", optional = true }
proptest-derive = { version = "0.3.0", optional = true }
tempfile = "3.3.0"

[build-dependencies]
framework = { path = ".." }
move-deps = { path = "../../move-deps" }

[features]
default = []
fuzzing = ["proptest", "proptest-derive"]
