{{- if .Values.service.fullnode.exposeApi }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "pfn.fullname" . }}
  labels:
    {{- include "pfn.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/tags: {{ .Values.service.aws_tags | quote }}
    {{- if .Values.ingress.loadBalancerSourceRanges }}
    alb.ingress.kubernetes.io/inbound-cidrs: {{ join "," .Values.ingress.loadBalancerSourceRanges }}
    {{- end }}
    {{- if .Values.service.domain }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.service.domain }}
    {{- end }}
    {{- if .Values.ingress.acm_certificate }}
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.acm_certificate }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    {{- end }}
    {{- if .Values.ingress.wafAclArn }}
    alb.ingress.kubernetes.io/wafv2-acl-arn: {{ .Values.ingress.wafAclArn }}
    {{- end }}
    {{- if .Values.ingress.enableStickyness }}
    alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds={{ .Values.ingress.cookieDurationSeconds }}
    alb.ingress.kubernetes.io/target-type: ip
    {{- end }}
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "pfn.fullname" . }}-fullnode
            port:
              number: 80
{{- end }}
  
