{{- $fullName := include "pfn.fullname" . -}}
{{- $labels := include "pfn.labels" . -}}
{{- $domain := .Values.service.domain -}}
{{- $loadBalancerSourceRanges := .Values.service.fullnode.loadBalancerSourceRanges -}}

{{- if .Values.service.fullnode.enableOnchainDiscovery }}
# create internet facing network address for fullnode 
# to allow onchain discovery
{{- range $i, $e := .Values.service.fullnode.numFullnodes | int | until }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-fullnode-%d" $fullName $i | quote }}
  labels:
    {{- $labels | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    {{- if $domain }}
    external-dns.alpha.kubernetes.io/hostname: {{ printf "pfn%d.%s" $i $domain | quote }}
    {{- end }}
    alb.ingress.kubernetes.io/healthcheck-path: /v1/-/healthy
spec:
  selector:
    app.kubernetes.io/instance: {{ printf "pfn%d" $i | quote }}
    app.kubernetes.io/part-of: aptos-fullnode
    app.kubernetes.io/name: fullnode
  ports:
  - name: aptosnet
    port: 6182
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerSourceRanges:
    {{- toYaml $loadBalancerSourceRanges | nindent 4 }}
---
{{- end }}
{{- end }}

{{- if .Values.service.fullnode.exposeApi }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pfn.fullname" . }}-fullnode
  labels:
    {{- include "pfn.labels" . | nindent 4 }}
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /v1/-/healthy
spec:
  selector:
    app.kubernetes.io/part-of: aptos-fullnode
    app.kubernetes.io/name: fullnode
  ports:
  - port: 80
    targetPort: 8080
  type: NodePort
  externalTrafficPolicy: Local
{{- end }}
