[package]
name = "consensus-types"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos consensus types"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.57"
bcs = "0.1.3"
futures = "0.3.12"
itertools = "0.10.3"
mirai-annotations = { version = "1.12.0", default-features = false }
proptest = { version = "1.0.0", optional = true }
serde = { version = "1.0.137", default-features = false }

aptos-bitvec = { path = "../../crates/aptos-bitvec" }
aptos-crypto = { path = "../../crates/aptos-crypto" }
aptos-crypto-derive = { path = "../../crates/aptos-crypto-derive" }
aptos-infallible = { path = "../../crates/aptos-infallible" }
aptos-types = { path = "../../types" }

executor-types = { path = "../../execution/executor-types" }
short-hex-str = { path = "../../crates/short-hex-str" }

[dev-dependencies]
proptest = "1.0.0"
serde_json = "1.0.81"

aptos-types = { path = "../../types", features = ["fuzzing"] }

[features]
default = []
fuzzing = ["proptest", "aptos-types/fuzzing", "aptos-crypto/fuzzing"]
