[package]
name = "aptos-logger"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos logger"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

# Do NOT add any inter-project dependencies.
# This is to avoid ever having a circular dependency with the aptos-logger crate.
[dependencies]
backtrace = { version = "0.3.58", features = ["serde"] }
chrono = "0.4.19"
console-subscriber = { version = "0.1.6", optional = true }
erased-serde = "0.3.13"
hostname = "0.3.1"
once_cell = "1.10.0"
prometheus = { version = "0.13.0", default-features = false }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
strum = "0.24.1"
strum_macros = "0.24.2"
tokio = { version = "1.18.2", features = ["full"] }
tracing = "0.1.34"
tracing-subscriber = "0.3.11"

aptos-infallible = { path = "../aptos-infallible" }
aptos-log-derive = { path = "../aptos-log-derive" }

[dev-dependencies]
pretty_assertions = "1.2.1"

[features]
default = []
aptos-console = ["tokio/tracing", "console-subscriber"]
