logging_sinks:
# this creates a `stdout` sink which writes all logs (again) to stdout. This is almost certainly not what you want in production - only useful for debugging.
# For production choose any (you can choose multiple) logging sinks supported by vector as found here https://vector.dev/docs/reference/configuration/sinks/
# stdout:
#   type: console
#   inputs: [kubernetes_logs]
#   encoding:
#     codec: json

# env:
#   - name: MY_CUSTOM_SECRET
#     valueFrom:
#       secretKeyRef:
#         name: custom-secret
#         key: MY_CUSTOM_SECRET

env:

# k8s_cluster: my_blockchain_cluster