[package]
name = "short-hex-str"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Short hex string encoding"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
mirai-annotations = "1.12.0"
serde = { version = "1.0.137", default-features = false }
static_assertions = "1.1.0"
thiserror = "1.0.31"

[dev-dependencies]
hex = "0.4.3"
proptest = "1.0.0"
