[package]
name = "aptos-warp-webserver"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos warp based webserver API"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.57"
aptos-api-types = { path = "../../api/types" }
aptos-config = { path = "../../config" }
aptos-logger = { path = "../../crates/aptos-logger" }
bcs = "0.1.3"
hyper = "0.14.18"
serde = { version = "1.0.137", features = ["derive"], default-features = false }
serde_json = { version = "1.0.81", features = ["preserve_order"] }
warp = { version = "0.3.2", features = ["default", "tls"] }
