# This compose file defines an Aptos Validator deployment.
# Read the README.md files for instruction on how to install aptos-node

version: "3.8"
services:
  validator:
    image: "${VALIDATOR_IMAGE_REPO:-aptoslabs/validator}:${IMAGE_TAG:-testnet}"
    networks:
      shared:
    volumes:
      - type: volume
        source: aptos-validator
        target: /opt/aptos/data
      - type: bind
        source: ./validator.yaml
        target: /opt/aptos/etc/validator.yaml
      - type: bind
        source: ./genesis.blob
        target: /opt/aptos/genesis/genesis.blob
      - type: bind
        source: ./waypoint.txt
        target: /opt/aptos/genesis/waypoint.txt
      - type: bind
        source: ./keys/validator-identity.yaml
        target: /opt/aptos/genesis/validator-identity.yaml
    command: ["/usr/local/bin/aptos-node", "-f", "/opt/aptos/etc/validator.yaml"]
    restart: unless-stopped
    ports:
      - "6180:6180"
      - "6181:6181"
      - "80:8080"
      - "9101:9101"
    expose:
      - 6180
      - 6181
      - 9101
      - 80

networks:
  shared:
    name: "aptos-docker-compose-shared"
    ipam:
      config:
        - subnet: 172.16.1.0/24

volumes:
  aptos-validator:
    name: aptos-validator
