[package]
name = "accumulator"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos merkle tree accumulator"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.57"
mirai-annotations = "1.12.0"
proptest = { version = "1.0.0", optional = true }

aptos-crypto = { path = "../../crates/aptos-crypto" }
aptos-types = { path = "../../types" }

[dev-dependencies]
proptest = "1.0.0"
rand = "0.7.3"

aptos-crypto = { path = "../../crates/aptos-crypto", features = ["fuzzing"] }

[features]
default = []
fuzzing = ["proptest", "aptos-crypto/fuzzing", "aptos-types/fuzzing"]
