[package]
name = "event-notifications"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
repository = "https://github.com/aptos-labs/aptos-core"
description = "The notification service offered by state sync for on-chain events"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
async-trait = "0.1.53"
futures = "0.3.21"
serde = { version = "1.0.137", default-features = false }
thiserror = "1.0.31"

aptos-id-generator = { path = "../../../crates/aptos-id-generator" }
aptos-infallible = { path = "../../../crates/aptos-infallible" }
aptos-state-view = { path = "../../../storage/state-view" }
aptos-types = { path = "../../../types" }

channel = { path = "../../../crates/channel" }
storage-interface = { path = "../../../storage/storage-interface" }

[dev-dependencies]
bcs = "0.1.3"
claim = "0.5.0"

aptos-crypto = { path = "../../../crates/aptos-crypto" }
aptos-temppath = { path = "../../../crates/aptos-temppath" }
aptos-vm = { path = "../../../aptos-move/aptos-vm" }
aptosdb = { path = "../../../storage/aptosdb" }
executor-test-helpers = { path = "../../../execution/executor-test-helpers" }
move-deps = { path = "../../../aptos-move/move-deps", features = ["address32"] }
vm-genesis = { path = "../../../aptos-move/vm-genesis", features = ["fuzzing"] }
