[package]
name = "schemadb"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos schemadb"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.57"
once_cell = "1.10.0"
proptest = { version = "1.0.0", optional = true }

aptos-infallible = { path = "../../crates/aptos-infallible" }
aptos-logger = { path = "../../crates/aptos-logger" }
aptos-metrics-core = { path = "../../crates/aptos-metrics-core" }

[dependencies.rocksdb]
version = "0.18.0"
default-features = false
features = ["lz4"]

[dev-dependencies]
byteorder = "1.4.3"
proptest = "1.0.0"

aptos-temppath = { path = "../../crates/aptos-temppath" }

[features]
fuzzing = ["proptest"]
