[package]
name = "vm-genesis"
version = "0.1.0"
edition = "2018"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos vm genesis"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false

[dependencies]
anyhow = "1.0.57"
bcs = "0.1.3"
once_cell = "1.10.0"
rand = "0.7.3"
serde = { version = "1.0.137", default-features = false }

aptos-config = { path = "../../config" }
aptos-crypto = { path = "../../crates/aptos-crypto" }
aptos-gas = { path = "../aptos-gas" }
aptos-state-view = { path = "../../storage/state-view" }
aptos-types = { path = "../../types" }
aptos-vm = { path = "../aptos-vm" }
cached-packages =  { path = "../framework/cached-packages" }

framework =  { path = "../framework" }
move-deps = { path = "../../aptos-move/move-deps", features = ["address32"] }

[dev-dependencies]
proptest = "1.0.0"
proptest-derive = "0.3.0"

aptos-proptest-helpers = { path = "../../crates/aptos-proptest-helpers" }
move-deps = { path = "../../aptos-move/move-deps", features = ["address32", "fuzzing"] }

[features]
default = []
fuzzing = ["aptos-types/fuzzing", "move-deps/fuzzing"]
