[package]
name = "aptos-state-view"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos state view"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.57"
bcs = "0.1.3"
move-deps = { path = "../../aptos-move/move-deps", features = ["address32"] }
serde = { version = "1.0.137", default-features = false }
serde_bytes = "0.11.6"
serde_json = "1.0.81"

aptos-crypto = { path = "../../crates/aptos-crypto" }
aptos-types = { path = "../../types" }

[features]
default = []
fuzzing = ["aptos-types/fuzzing"]
