AllCops:
  Exclude:
    - db/schema.rb
    - vendor/**/*
  NewCops: enable

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 20

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 100

Metrics/ClassLength:
  Max: 200

Style/Copyright:
  Enabled: true
  Notice: '^# Copyright \(c\) Aptos'
  AutocorrectNotice: "# Copyright (c) Aptos\n# SPDX-License-Identifier: Apache-2.0\n"

Style/FrozenStringLiteralComment:
  Enabled: true
  SafeAutoCorrect: true # it is safe to add frozen_string_literal: true

Lint/MissingSuper:
  Exclude:
    - 'app/components/**/*'

Style/DoubleNegation:
  Enabled: false
