[package]
name = "network-builder"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos network builder for constructing a network"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.53"
bcs = "0.1.3"
futures = "0.3.21"
rand = "0.7.3"
serde = { version = "1.0.137", default-features = false }
tokio = { version = "1.18.2", features = ["full"] }

aptos-config = { path = "../../config" }
aptos-crypto = { path = "../../crates/aptos-crypto" }
aptos-infallible = { path = "../../crates/aptos-infallible" }
aptos-logger = { path = "../../crates/aptos-logger" }
aptos-secure-storage = { path = "../../secure/storage" }
aptos-time-service = { path = "../../crates/aptos-time-service", features = ["async"] }
aptos-types = { path = "../../types" }

channel = { path = "../../crates/channel" }
event-notifications = { path = "../../state-sync/inter-component/event-notifications" }
netcore = { path = "../netcore" }
network = { path = "../." }
network-discovery = { path = "../discovery" }
