[package]
name = "backup-cli"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.57"
async-trait = "0.1.53"
bcs = "0.1.3"
bytes = "1.1.0"
futures = "0.3.21"
itertools = "0.10.0"
num_cpus = "1.13.1"
once_cell = "1.10.0"
pin-project = "1.0.10"
rand = "0.7.3"
regex = "1.5.5"
reqwest = { version = "0.11.10", features = ["stream"], default-features = false }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
structopt = "0.3.21"
tokio = { version = "1.18.2", features = ["full"] }
tokio-stream = "0.1.8"
tokio-util = { version = "0.7.2", features = ["compat"] }
toml = "0.5.9"

aptos-config = { path = "../../../config" }
aptos-crypto = { path = "../../../crates/aptos-crypto" }
aptos-infallible = { path = "../../../crates/aptos-infallible" }
aptos-jellyfish-merkle = { path = "../../jellyfish-merkle" }
aptos-logger = { path = "../../../crates/aptos-logger" }
aptos-push-metrics = { path = "../../../crates/aptos-push-metrics" }
aptos-temppath = { path = "../../../crates/aptos-temppath" }
aptos-types = { path = "../../../types" }
aptos-vm = { path = "../../../aptos-move/aptos-vm" }

aptosdb = { path = "../../aptosdb" }
executor = { path = "../../../execution/executor" }
executor-test-helpers = { path = "../../../execution/executor-test-helpers", optional = true }
executor-types = { path = "../../../execution/executor-types" }
scratchpad = { path = "../../scratchpad" }
storage-interface = { path = "../../storage-interface" }

[dev-dependencies]
proptest = "1.0.0"
warp = "0.3.2"

aptos-config = { path = "../../../config" }
aptos-proptest-helpers = { path = "../../../crates/aptos-proptest-helpers" }
aptosdb = { path = "../../aptosdb", features = ["fuzzing"] }
backup-service = { path = "../backup-service" }
executor-test-helpers = { path = "../../../execution/executor-test-helpers" }
storage-interface = { path = "../../storage-interface" }

[features]
fuzzing = ["aptosdb/fuzzing"]
