[package]
name = "forge-cli"
version = "0.0.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos end to end test framework CLI"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.57"
async-trait = "0.1.53"
structopt = "0.3.21"
tokio = { version = "1.18.2", features = ["full"] }
url = "2.2.2"

aptos-logger = { path = "../../crates/aptos-logger" }
aptos-rest-client = { path = "../../crates/aptos-rest-client" }
aptos-sdk = { path = "../../sdk" }
cached-packages = { path = "../../aptos-move/framework/cached-packages" }
forge = { path = "../forge" }

framework = { path = "../../aptos-move/framework" }
testcases = { path = "../testcases" }

[[bin]]
name = "forge"
path = "src/main.rs"
