[package]
name = "aptos-secure-storage"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
repository = "https://github.com/aptos-labs/aptos-core"
description = "Aptos's Persistent, Secure Storage"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.57"
base64 = "0.13.0"
bcs = "0.1.3"
chrono = "0.4.19"
enum_dispatch = "0.3.8"
rand = "0.7.3"
serde = { version = "1.0.137", features = ["rc"], default-features = false }
serde_json = "1.0.81"
thiserror = "1.0.31"

aptos-crypto = { path = "../../crates/aptos-crypto" }
aptos-github-client = { path = "github" }
aptos-infallible = { path = "../../crates/aptos-infallible" }
aptos-logger = { path = "../../crates/aptos-logger" }
aptos-temppath = { path = "../../crates/aptos-temppath" }
aptos-time-service = { path = "../../crates/aptos-time-service" }
aptos-vault-client = { path = "vault" }
schemadb = { path = "../../storage/schemadb" }

[dev-dependencies]
rand = "0.7.3"

aptos-crypto = { path = "../../crates/aptos-crypto", features = ["fuzzing"] }
aptos-crypto-derive = { path = "../../crates/aptos-crypto-derive" }
schemadb = { path = "../../storage/schemadb", features = ["fuzzing"] }

[features]
fuzzing = ["aptos-crypto/fuzzing"]
testing = []
