[package]
name = "executor"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos executor"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.57"
bcs = "0.1.3"
fail = "0.5.0"
itertools = { version = "0.10.0", default-features = false }
once_cell = "1.10.0"
rayon = "1.5.2"
serde = { version = "1.0.137", features = ["derive"] }

aptos-crypto = { path = "../../crates/aptos-crypto" }
aptos-infallible = { path = "../../crates/aptos-infallible" }
aptos-logger = { path = "../../crates/aptos-logger" }
aptos-metrics-core = { path = "../../crates/aptos-metrics-core" }
aptos-secure-net = { path = "../../secure/net" }
aptos-state-view = { path = "../../storage/state-view" }
aptos-types = { path = "../../types" }
aptos-vm = { path = "../../aptos-move/aptos-vm" }

consensus-types = { path = "../../consensus/consensus-types" }
executor-types = { path = "../executor-types" }
move-deps = { path = "../../aptos-move/move-deps", features = ["address32"] }
scratchpad = { path = "../../storage/scratchpad" }
storage-interface = { path = "../../storage/storage-interface" }

[dev-dependencies]
proptest = "1.0.0"
rand = "0.7.3"

aptos-config = { path = "../../config" }
aptos-genesis = { path = "../../crates/aptos-genesis", features = ["testing"] }
aptos-temppath = { path = "../../crates/aptos-temppath" }
aptos-types = { path = "../../types", features = ["fuzzing"] }
aptosdb = { path = "../../storage/aptosdb" }
cached-packages = { path = "../../aptos-move/framework/cached-packages" }
executor-test-helpers = { path = "../executor-test-helpers" }
move-deps = { path = "../../aptos-move/move-deps" }
storage-interface = { path = "../../storage/storage-interface", features = ["fuzzing"] }
vm-genesis = { path = "../../aptos-move/vm-genesis" }

[features]
default = []
fuzzing = ["consensus-types/fuzzing", "aptos-crypto/fuzzing", "aptos-types/fuzzing", "storage-interface/fuzzing"]
failpoints = ["fail/failpoints", "aptos-vm/failpoints"]
