[package]
name = "aptos-rosetta-cli"
version = "0.0.1"
description = "Aptos Rosetta CLI for testing"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
edition = "2018"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false

[dependencies]
anyhow = "1.0.57"
clap = "3.1.18"
hex = "0.4.3"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
tokio = { version = "1.18.2", features = ["full", "time"] }
url = "2.2.2"

aptos = { path = "../aptos" }
aptos-config = { path = "../../config" }
aptos-crypto = { path = "../aptos-crypto", features = ["fuzzing"] }
aptos-logger = { path = "../aptos-logger" }
aptos-rosetta = { path = "../aptos-rosetta" }
aptos-types = { path = "../../types" }

