[package]
name = "transaction-emitter-lib"
version = "0.0.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Library for Aptos transaction emitter"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
again = "0.1.2"
anyhow = { version = "1.0.57", features = ["backtrace"] }
clap = "3.1.17"
futures = "0.3.21"
itertools = "0.10.3"
once_cell = "1.10.0"
rand = "0.7.3"
rand_core = "0.5.1"
reqwest = { version = "0.11.10", features = ["blocking", "json"] }
serde = { version = "1.0.137", features = ["derive"] }
termion = "1.5.6"
tokio = { version = "1.18.2", features = ["full"] }
url = { version = "2.2.2", features = ["serde"] }

aptos = { path = "../aptos" }
aptos-config = { path = "../../config" }
aptos-crypto = { path = "../aptos-crypto" }
aptos-logger = { path = "../../crates/aptos-logger" }
aptos-rest-client = { path = "../aptos-rest-client" }
aptos-sdk = { path = "../../sdk" }
