[package]
name = "aptosdb"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos database"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.57"
arc-swap = "1.5.0"
arr_macro = "0.1.3"
bcs = "0.1.3"
byteorder = "1.4.3"
itertools = "0.10.0"
lru = "0.7.7"
num-derive = "0.3.3"
num-traits = "0.2.15"
once_cell = "1.10.0"
proptest = { version = "1.0.0", optional = true }
proptest-derive = { version = "0.3.0", optional = true }
rayon = "1.5.2"
serde = "1.0.137"
thiserror = "1.0.31"

accumulator = { path = "../accumulator" }
aptos-config = { path = "../../config" }
aptos-crypto = { path = "../../crates/aptos-crypto" }
aptos-infallible = { path = "../../crates/aptos-infallible" }
aptos-jellyfish-merkle = { path = "../jellyfish-merkle" }
aptos-logger = { path = "../../crates/aptos-logger" }
aptos-metrics-core = { path = "../../crates/aptos-metrics-core" }
aptos-proptest-helpers = { path = "../../crates/aptos-proptest-helpers", optional = true }
aptos-rocksdb-options = { path = "../rocksdb-options" }
aptos-state-view = { path = "../state-view" }
aptos-temppath = { path = "../../crates/aptos-temppath", optional = true }
aptos-types = { path = "../../types" }
aptos-vm = { path = "../../aptos-move/aptos-vm" }
aptosdb-indexer = { path = "../indexer" }

executor-types = { path = "../../execution/executor-types" }
move-deps = { path = "../../aptos-move/move-deps", features = ["address32"] }
num-variants = { path = "../../crates/num-variants" }
schemadb = { path = "../schemadb" }
scratchpad = { path = "../scratchpad" }
storage-interface = { path = "../storage-interface" }

[dev-dependencies]
proptest = "1.0.0"
proptest-derive = "0.3.0"
rand = "0.7.3"

aptos-jellyfish-merkle = { path = "../jellyfish-merkle", features = ["fuzzing"] }
aptos-proptest-helpers = { path = "../../crates/aptos-proptest-helpers" }
aptos-temppath = { path = "../../crates/aptos-temppath" }
aptos-types = { path = "../../types", features = ["fuzzing"] }
executor-types = { path = "../../execution/executor-types", features = ["fuzzing"] }
schemadb = { path = "../schemadb", features = ["fuzzing"] }
scratchpad = { path = "../scratchpad", features = ["fuzzing"] }

[features]
default = []
fuzzing = ["proptest", "proptest-derive", "aptos-proptest-helpers", "aptos-temppath", "aptos-crypto/fuzzing", "aptos-jellyfish-merkle/fuzzing", "aptos-types/fuzzing", "executor-types/fuzzing", "schemadb/fuzzing", "scratchpad/fuzzing"]
