[package]
name = "aptos-jellyfish-merkle"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos jellyfish merkle"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.57"
bcs = "0.1.3"
byteorder = "1.4.3"
itertools = { version = "0.10.0", default-features = false }
mirai-annotations = "1.12.0"
num-derive = "0.3.3"
num-traits = "0.2.15"
once_cell = "1.10.0"
proptest = { version = "1.0.0", optional = true }
proptest-derive = { version = "0.3.0", optional = true }
rayon = "1.5.2"
serde = { version = "1.0.137", features = ["derive"] }
thiserror = "1.0.31"

aptos-crypto = { path = "../../crates/aptos-crypto" }
aptos-crypto-derive = { path = "../../crates/aptos-crypto-derive" }
aptos-infallible = { path = "../../crates/aptos-infallible" }
aptos-logger = { path = "../../crates/aptos-logger" }
aptos-metrics-core = { path = "../../crates/aptos-metrics-core" }
aptos-types = { path = "../../types" }

storage-interface = { path = "../storage-interface" }

[dev-dependencies]
proptest = "1.0.0"
proptest-derive = "0.3.0"
rand = "0.7.3"

aptos-crypto = { path = "../../crates/aptos-crypto", features = ["fuzzing"] }
aptos-types = { path = "../../types", features = ["fuzzing"] }
aptosdb = { path = "../aptosdb", features = ["fuzzing"] }

[features]
default = []
fuzzing = ["proptest", "proptest-derive", "aptos-crypto/fuzzing", "aptos-types/fuzzing"]
