[package]
name = "aptos-openapi"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Helpers that allow structs to self-describe in an OpenAPI spec"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
async-trait = "0.1.53"
mime = "0.3.16"
percent-encoding = "2.1.0"
poem = { git = "https://github.com/poem-web/poem", rev = "f39eba95cbfb52989e0eff516dad86719dc7dcba" }
poem-openapi = { git = "https://github.com/poem-web/poem", rev = "f39eba95cbfb52989e0eff516dad86719dc7dcba" }
serde = { version = "1.0.137", default-features = false }
serde_json = "1.0.81"
