runs:
  using: composite
  steps:
    - run: sudo apt-get update && sudo apt-get install build-essential ca-certificates clang curl git libpq-dev libssl-dev pkg-config --no-install-recommends --assume-yes
      shell: bash
    - uses: actions-rs/toolchain@v1
      with:
        override: true
        components: rustfmt, clippy
    - uses: bmwill/rust-cache@v1
      with:
        path: ~/.cargo/registry/src/**/librocksdb-sys-*
    - name: install Prover dependencies
      shell: bash
      run: scripts/dev_setup.sh -b -p -r -y
    - name: prepare move lang prover tooling.
      shell: bash
      run: |
        # By setting these values the dev-setup.sh script can detect already installed executables (and check versions).
        echo 'Z3_EXE='/home/runner/bin/z3 | tee -a $GITHUB_ENV
        echo 'CVC5_EXE='/home/runner/bin/cvc5 | tee -a $GITHUB_ENV
        echo 'DOTNET_ROOT='/home/runner/.dotnet/ | tee -a $GITHUB_ENV
        echo 'BOOGIE_EXE='/home/runner/.dotnet/tools/boogie | tee -a $GITHUB_ENV
        echo 'MVP_TEST_ON_CI'='1' | tee -a $GITHUB_ENV
        echo "/home/runner/bin" | tee -a $GITHUB_PATH
        echo "/home/runner/.dotnet" | tee -a $GITHUB_PATH
        echo "/home/runner/.dotnet/tools" | tee -a $GITHUB_PATH
        echo "/home/runner/.cargo/bin" | tee -a $GITHUB_PATH
