[package]
name = "aptos-retrier"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Generic retry and exponential backoff"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
tokio = { version = "1.18.2", features = ["time"] }

aptos-logger = { path = "../../crates/aptos-logger" }

