[package]
name = "consensus"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos consensus"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.57"
async-trait = "0.1.53"
bcs = "0.1.3"
byteorder = { version = "1.4.3" }
bytes = "1.1.0"
fail = "0.5.0"
futures = "0.3.21"
itertools = { version = "0.10.3", default-features = false }
mirai-annotations = { version = "1.12.0", default-features = false }
num-derive = { version = "0.3.3", default-features = false }
num-traits = { version = "0.2.15", default-features = false }
once_cell = "1.10.0"
rand = { version = "0.7.3", default-features = false }
serde = { version = "1.0.137", default-features = false }
serde_json = "1.0.81"
termion = { version = "1.5.6", default-features = false }
thiserror = "1.0.31"
tokio = { version = "1.18.2", features = ["full"] }

aptos-bitvec = { path = "../crates/aptos-bitvec" }
aptos-config = { path = "../config" }
aptos-crypto = { path = "../crates/aptos-crypto" }
aptos-infallible = { path = "../crates/aptos-infallible" }
aptos-keygen = { path = "../crates/aptos-keygen" }
aptos-logger = { path = "../crates/aptos-logger" }
aptos-mempool = { path = "../mempool" }
aptos-metrics-core = { path = "../crates/aptos-metrics-core" }
aptos-secure-storage = { path = "../secure/storage" }
aptos-temppath = { path = "../crates/aptos-temppath" }
aptos-types = { path = "../types" }
aptos-vm = { path = "../aptos-move/aptos-vm" }

channel = { path = "../crates/channel" }
consensus-notifications = { path = "../state-sync/inter-component/consensus-notifications" }
consensus-types = { path = "consensus-types", default-features = false }
event-notifications = { path = "../state-sync/inter-component/event-notifications" }
executor = { path = "../execution/executor" }
executor-types = { path = "../execution/executor-types" }
fallible = { path = "../crates/fallible" }
network = { path = "../network" }
safety-rules = { path = "safety-rules" }
schemadb = { path = "../storage/schemadb" }
short-hex-str = { path = "../crates/short-hex-str" }
storage-interface = { path = "../storage/storage-interface" }

[dev-dependencies]
claim = "0.5.0"
proptest = "1.0.0"
tempfile = "3.3.0"

aptos-config = { path = "../config", features = ["fuzzing"] }
aptos-mempool = { path = "../mempool", features = ["fuzzing"] }
consensus-types = { path = "consensus-types", default-features = false, features = ["fuzzing"] }
executor-test-helpers = { path = "../execution/executor-test-helpers" }
move-deps = { path = "../aptos-move/move-deps", features = ["address32"] }
network = { path = "../network", features = ["fuzzing"] }
safety-rules = { path = "safety-rules", features = ["testing"] }
vm-validator = { path = "../vm-validator" }

[features]
default = []
fuzzing = ["consensus-types/fuzzing", "aptos-config/fuzzing", "aptos-crypto/fuzzing", "aptos-mempool/fuzzing", "aptos-types/fuzzing", "safety-rules/testing"]
failpoints = ["fail/failpoints"]
