kind: NetworkChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: {namespace}
  name: forge-namespace-{latency_ms}ms-latency
spec:
  selector:
    namespaces:
      - {namespace}
    labelSelectors:
      app.kubernetes.io/name: validator
  mode: all
  action: delay
  delay:
    latency: "{latency_ms}ms"
    correlation: "{correlation_percentage}"
    jitter: "{jitter_ms}ms"
  # Indicates the direction of target packets. Available vaules include:
  # from (the packets from target)
  # to (the packets to target)
  # both ( the packets from or to target)
  # This parameter makes Chaos only take effect for a specific direction of packets.
  direction: to
  target:
    selector:
      namespaces:
        - {namespace}
      labelSelectors:
        app.kubernetes.io/name: validator
    mode: all
