[package]
name = "e2e-move-tests"
version = "0.1.0"
edition = "2018"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Move e2e tests"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false

[dependencies]
anyhow = "1.0.59"
bcs = "0.1.3"
itertools = "0.10.0"
project-root = "0.2.2"
proptest = "1.0.0"
serde = { version = "1.0.137", default-features = false }
tempfile = "3.3.0"

aptos = { path = "../../crates/aptos" }
aptos-crypto = { path = "../../crates/aptos-crypto", features = ["fuzzing"] }
aptos-keygen = { path = "../../crates/aptos-keygen" }
aptos-logger = { path = "../../crates/aptos-logger" }
aptos-parallel-executor = { path = "../parallel-executor" }
aptos-state-view = { path = "../../storage/state-view" }
aptos-types = { path = "../../types", features = ["fuzzing"] }
aptos-vm = { path = "../aptos-vm", features = ["fuzzing"] }
cached-packages = { path = "../framework/cached-packages" }
framework = { path = "../framework" }
vm-genesis = { path = "../vm-genesis" }

aptos-writeset-generator = { path = "../writeset-transaction-generator" }
language-e2e-tests = { path = "../e2e-tests" }
move-deps = { path = "../move-deps", features = ["address32"] }

[lib]
doctest = false
