[package]
name = "aptos-substreams"
version = "0.0.1"
description = "Substreams for Aptos Chain"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0.137", default-features = false }
serde_json = "1.0.81"
substreams = "0.0.17"

aptos-protos = { path = "../../../crates/aptos-protos" }

# This is the difference between a multi MB binary, and a few hundred KB binary
[profile.release]
lto = true
opt-level = 's'
strip = "debuginfo"
