[package]
name = "aptos-fuzzer"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos fuzzer"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.57"
bcs = "0.1.3"
byteorder = { version = "1.4.3", default-features = false }
hex = "0.4.3"
once_cell = "1.10.0"
proptest = { version = "1.0.0", default-features = false }
proptest-derive = { version = "0.3.0", default-features = false }
rand = "0.7.3"
rusty-fork = { version = "0.3.0", default-features = false }
sha-1 = { version = "0.10.0", default-features = false }
structopt = "0.3.21"

accumulator = { path = "../../storage/accumulator", features = ["fuzzing"] }
aptos-crypto = { path = "../../crates/aptos-crypto", features = ["fuzzing"] }
aptos-jellyfish-merkle = { path = "../../storage/jellyfish-merkle", features = ["fuzzing"] }
aptos-mempool = { path = "../../mempool" }
aptos-proptest-helpers = { path = "../../crates/aptos-proptest-helpers" }
aptos-types = { path = "../../types", features = ["fuzzing"] }
aptos-vault-client = { path = "../../secure/storage/vault", features = ["fuzzing"] }

aptosdb = { path = "../../storage/aptosdb", features = ["fuzzing"] }
consensus = { path = "../../consensus", features = ["fuzzing"] }
consensus-types = { path = "../../consensus/consensus-types", features = ["fuzzing"] }
executor = { path = "../../execution/executor", features = ["fuzzing"] }
executor-types = { path = "../../execution/executor-types", features = ["fuzzing"] }
language-e2e-tests = { path = "../../aptos-move/e2e-tests" }
move-deps = { path = "../../aptos-move/move-deps", features = ["fuzzing"] }
network = { path = "../../network", features = ["fuzzing"] }
safety-rules = { path = "../../consensus/safety-rules", features = ["fuzzing", "testing"] }
scratchpad = { path = "../../storage/scratchpad", features = ["fuzzing"] }
storage-interface = { path = "../../storage/storage-interface" }

[dev-dependencies]
datatest-stable = "0.1.1"
rusty-fork = "0.3.0"
stats_alloc = "0.1.8"

[[test]]
harness = false
name = "artifacts"
