[package]
name = "safety-rules"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos safety rules"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
once_cell = "1.10.0"
proptest = { version = "1.0.0", optional = true }
rand = { version = "0.7.3", default-features = false }
serde = { version = "1.0.137", default-features = false }
serde_json = "1.0.81"
thiserror = "1.0.31"

aptos-config = { path = "../../config" }
aptos-crypto = { path = "../../crates/aptos-crypto" }
aptos-global-constants = { path = "../../config/global-constants" }
aptos-infallible = { path = "../../crates/aptos-infallible" }
aptos-logger = { path = "../../crates/aptos-logger" }
aptos-metrics-core = { path = "../../crates/aptos-metrics-core" }
aptos-proptest-helpers = { path = "../../crates/aptos-proptest-helpers", optional = true }
aptos-secure-net = { path = "../../secure/net" }
aptos-secure-storage = { path = "../../secure/storage" }
aptos-temppath = { path = "../../crates/aptos-temppath" }
aptos-types = { path = "../../types" }
aptos-vault-client = { path = "../../secure/storage/vault" }

consensus-types = { path = "../consensus-types" }
crash-handler = { path = "../../crates/crash-handler" }

[dev-dependencies]
criterion = "0.3.5"
proptest = "1.0.0"
rusty-fork = "0.3.0"
tempfile = "3.3.0"

aptos-config = { path = "../../config", features = ["fuzzing"] }
aptos-proptest-helpers = { path = "../../crates/aptos-proptest-helpers" }
aptos-secure-storage = { path = "../../secure/storage", features = ["testing"] }
consensus-types = { path = "../consensus-types", features = ["fuzzing"] }

[[bench]]
name = "safety_rules"
harness = false
required-features = ["testing"]

[features]
default = []
fuzzing = ["consensus-types/fuzzing", "aptos-config/fuzzing", "proptest", "aptos-proptest-helpers"]
testing = ["aptos-secure-storage/testing"]
