[package]
name = "aptos-crypto"
version = "0.0.3"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos crypto"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = ["crates-io"]
edition = "2018"

[dependencies]
anyhow = "1.0.57"
bcs = "0.1.3"
blst = "0.3.7"
bytes = "1.1.0"
curve25519-dalek = { version = "3", default-features = false }
digest = "0.9.0"
ed25519-dalek = { version = "1.0.1", features = ["std", "serde"] }
hex = "0.4.3"
hkdf = "0.10.0"
mirai-annotations = "1.12.0"
once_cell = "1.10.0"
proptest = { version = "1.0.0", optional = true }
proptest-derive = { version = "0.3.0", optional = true }
rand = "0.7.3"
rand_core = { version = "0.5.1", default-features = false }
ring = { version = "0.16.20", features = ["std"] }
serde = { version = "1.0.137", features = ["derive"] }
serde-name = "0.1.1"
serde_bytes = "0.11.6"
sha2 = "0.9.3"
static_assertions = "1.1.0"
thiserror = "1.0.31"
tiny-keccak = { version = "2.0.2", features = ["sha3"] }
x25519-dalek = { version = "1.2.0" }

aptos-crypto-derive = { path = "../aptos-crypto-derive", version = "0.0.3" }

[dev-dependencies]
bitvec = "0.19.4"
byteorder = "1.4.3"
criterion = "0.3.5"
proptest = "1.0.0"
proptest-derive = "0.3.0"
serde_json = "1.0.81"
sha3 = "0.9.1"
trybuild = "1.0.41"

[features]
default = []
assert-private-keys-not-cloneable = []
cloneable-private-keys = []
fuzzing = ["proptest", "proptest-derive", "cloneable-private-keys"]

[[bench]]
name = "noise"
harness = false

[[bench]]
name = "ed25519"
harness = false

[[bench]]
name = "bls12381"
harness = false
