data_dir: /vector-data-dir
api:
  enabled: true
  address: 127.0.0.1:8686
  playground: false
sources:
  kubernetes_logs:
    type: kubernetes_logs
  host_metrics:
    filesystem:
      devices:
        excludes: [binfmt_misc]
      filesystems:
        excludes: [binfmt_misc]
      mountPoints:
        excludes: ["*/proc/sys/fs/binfmt_misc"]
    type: host_metrics
  internal_metrics:
    type: internal_metrics
transforms:
  k8s_logs:
    type: remap
    inputs:
      - kubernetes_logs
    source: |-
      .k8s = del(.kubernetes)
      .k8s.cluster = "${K8S_CLUSTER:?err}"
sinks:
  prom_exporter:
    type: prometheus_exporter
    inputs: [host_metrics, internal_metrics]
    address: 0.0.0.0:9090
    # HACK ALARM: need to replace the observe customer id expression with a 'quoted' version of it here, otherwise vector's environment
    # variable substitution will treat the customer id as an integer value which will fail vector's config 
  {{- toYaml .Values.logging_sinks | nindent 2 | replace "${OBSERVE_CUSTOMER_ID:?err}" "'${OBSERVE_CUSTOMER_ID:?err}'"}}
