[package]
name = "aptos-time-service"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Time Service for mocking time with tokio"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
enum_dispatch = "0.3.8"
futures = { version = "0.3.12", optional = true }
pin-project = { version = "1.0.10", optional = true }
thiserror = "1.0.31"
tokio = { version = "1.18.2", features = ["macros", "rt-multi-thread", "time"], optional = true }

aptos-infallible = { path = "../../crates/aptos-infallible" }

[dev-dependencies]
futures = "0.3.21"
pin-project = "1.0.10"
tokio = { version = "1.18.2", features = ["macros", "rt-multi-thread", "time"] }
tokio-test = "0.4.1"

[features]
default = []
async = ["futures", "pin-project", "tokio"]
testing = ["async"]
