[package]
name = "bounded-executor"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Executor bounded by number of concurrent tasks"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
futures = "0.3.21"
tokio = { version = "1.18.2", features = ["sync", "rt"] }

[dev-dependencies]
tokio = { version = "1.18.2", features = ["full"] }
