[package]
name = "aptos-data-client"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "The Aptos data client"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
async-trait = "0.1.53"
futures = "0.3.21"
itertools = "0.10.0"
rand = "0.7.3"
serde = { version = "1.0.137", default-features = false }
thiserror = "1.0.31"
tokio = { version = "1.18.2", features = ["full"] }

aptos-config = { path = "../../config" }
aptos-crypto = { path = "../../crates/aptos-crypto" }
aptos-id-generator = { path = "../../crates/aptos-id-generator" }
aptos-infallible = { path = "../../crates/aptos-infallible" }
aptos-logger = { path = "../../crates/aptos-logger" }
aptos-metrics-core = { path = "../../crates/aptos-metrics-core" }
aptos-time-service = { path = "../../crates/aptos-time-service", features = ["async"] }
aptos-types = { path = "../../types" }

netcore = { path = "../../network/netcore" }
network = { path = "../../network" }
short-hex-str = { path = "../../crates/short-hex-str" }
storage-service-client = { path = "../storage-service/client" }
storage-service-types = { path = "../storage-service/types" }

[dev-dependencies]
bcs = "0.1.3"
claim = "0.5.0"
maplit = "1.0.2"
tokio = { version = "1.18.2", features = ["rt", "macros"], default-features = false }

aptos-time-service = { path = "../../crates/aptos-time-service", features = ["async", "testing"] }
channel = { path = "../../crates/channel" }
network = { path = "../../network", features = ["fuzzing"] }
storage-service-server = { path = "../storage-service/server" }
