[package]
name = "aptos-proptest-helpers"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos proptest helpers"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
crossbeam = "0.8.1"
proptest = "1.0.0"
proptest-derive = "0.3.0"


