[package]
name = "aptos-vault-client"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
repository = "https://github.com/aptos-labs/aptos-core"
description = "Aptos's Restful Vault Client"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
base64 = "0.13.0"
chrono = "0.4.19"
native-tls = "0.2.10"
once_cell = "1.10.0"
proptest = { version = "1.0.0", optional = true }
serde = { version = "1.0.137", features = ["derive"], default-features = false }
serde_json = "1.0.81"
thiserror = "1.0.31"
ureq = { version = "1.5.4", features = ["json", "native-tls"], default-features = false }

aptos-crypto = { path = "../../../crates/aptos-crypto" }
aptos-proptest-helpers = { path = "../../../crates/aptos-proptest-helpers", optional = true }
aptos-types = { path = "../../../types", optional = true }

[dev-dependencies]
proptest = "1.0.0"

aptos-proptest-helpers = { path = "../../../crates/aptos-proptest-helpers" }
aptos-types = { path = "../../../types", features = ["fuzzing"] }

[features]
fuzzing = ["proptest", "aptos-proptest-helpers", "aptos-types", "aptos-types/fuzzing"]
