[package]
name = "aptos-fuzz"
version = "0.1.0"
edition = "2018"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos fuzzer fuzz"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "=0.3.2"
once_cell = "1.10.0"

aptos-fuzzer = { path = ".." }

[[bin]]
name = "fuzz_runner"
path = "fuzz_targets/fuzz_runner.rs"
test = false

# used for integration with Google OSS-Fuzz (see README)
[[bin]]
name = "fuzzer_builder"
path = "google-oss-fuzz/fuzzer_builder.rs"
test = false
