[package]
name = "aptos-api"
version = "0.2.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos REST API"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.57"
async-trait = "0.1.53"
bcs = "0.1.3"
bytes = "1.1.0"
fail = "0.5.0"
futures = "0.3.21"
hex = "0.4.3"
hyper = "0.14.18"
mime = "0.3.16"
once_cell = "1.10.0"
paste = "1.0.7"
percent-encoding = "2.1.0"
poem = { git = "https://github.com/poem-web/poem", rev = "f39eba95cbfb52989e0eff516dad86719dc7dcba", features = ["anyhow", "rustls"] }
poem-openapi = { git = "https://github.com/poem-web/poem", rev = "f39eba95cbfb52989e0eff516dad86719dc7dcba", features = ["url"] }
serde = { version = "1.0.137", features = ["derive"], default-features = false }
serde_json = { version = "1.0.81", features = ["preserve_order"] }
thiserror = "1.0.31"
tokio = { version = "1.18.2", features = ["full"] }
url = "2.2.2"

aptos-api-types = { path = "./types", package = "aptos-api-types" }
aptos-config = { path = "../config" }
aptos-crypto = { path = "../crates/aptos-crypto" }
aptos-logger = { path = "../crates/aptos-logger" }
aptos-mempool = { path = "../mempool" }
aptos-metrics-core = { path = "../crates/aptos-metrics-core" }
aptos-state-view = { path = "../storage/state-view" }
aptos-types = { path = "../types" }
aptos-vm = { path = "../aptos-move/aptos-vm" }

move-deps = { path = "../aptos-move/move-deps", features = ["address32"] }
storage-interface = { path = "../storage/storage-interface" }

[dev-dependencies]
aptos-api-test-context = { path = "./test-context", package = "aptos-api-test-context" }
aptos-crypto = { path = "../crates/aptos-crypto" }
aptos-genesis = { path = "../crates/aptos-genesis", features = ["testing"] }
aptos-global-constants = { path = "../config/global-constants" }
aptos-mempool = { path = "../mempool", features = ["fuzzing"] }
aptos-proptest-helpers = { path = "../crates/aptos-proptest-helpers" }
aptos-sdk = { path = "../sdk" }
aptos-secure-storage = { path = "../secure/storage" }
aptos-temppath = { path = "../crates/aptos-temppath" }
aptos-vm = { path = "../aptos-move/aptos-vm" }
aptosdb = { path = "../storage/aptosdb", features = ["fuzzing"] }
executor = { path = "../execution/executor" }
executor-types = { path = "../execution/executor-types" }
framework = { path = "../aptos-move/framework" }
goldenfile = "1.1.0"
mempool-notifications = { path = "../state-sync/inter-component/mempool-notifications" }
move-deps = { path = "../aptos-move/move-deps" }
proptest = { version = "1.0.0", default-features = true }
rand = "0.7.3"
regex = "1.5.5"
reqwest = { version = "0.11.10", features = ["blocking", "json"], default_features = false }
serde_path_to_error = "0.1"
vm-validator = { path = "../vm-validator" }
warp = { version = "0.3.2", features = ["default"] }
warp-reverse-proxy = "0.5.0"

[features]
failpoints = ["fail/failpoints"]
