# This set of CI steps checks that the docs site examples work against devnet.
# These steps don't guarantee that the examples will never break, since the
# devnet release, SDK release, and examples release are all indepdent events.
# So this check should never be marked land blocking, since there is an
# unavoidable period of time where they will be incompatible with each devnet
# release. Instead, this should serve as a notification that the examples are
# broken, so we notice that they're broken before the community does.

# Explaining another way, there are two types of compatability we check:
#   - Compatibility between SDK and node on a particular commit
#   - Compatibility between SDK on package manager and node on devnet
#
# This CI checks the second type of compatability, the sdk-release.yaml CI
# steps check the first type.

name: "Check docs site examples"
on:
  pull_request:
  push:
    branches:
      - main
      - devnet

# Cancel redundant runs
concurrency:
  # for push and workflow_dispatch events we use `github.sha` in the concurrency group and don't really cancel each other out/limit concurrency
  # for pull_request events newer jobs cancel earlier jobs to save on CI etc.
  group: ${{ github.workflow }}-${{ (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.sha || github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  # In case of pull_request events by default github actions merges main into the PR branch and then runs the tests etc
  # on the prospective merge result instead of only on the tip of the PR.
  # For more info also see https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit
  GIT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}

# These tests are being run against devnet. To combat flakiness resulting from
# chatting with a remote service, each test is run with retries.
jobs:
  # Note: We do not check first_coin or hello_blockchain yet.
  test-ts-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.GIT_SHA }}

      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          registry-url: 'https://registry.npmjs.org'

      - run: cd ./developer-docs-site/static/examples/typescript && yarn install

      - uses: nick-fields/retry@v2
        name: first_transaction
        with:
          max_attempts: 3
          timeout_minutes: 15
          command: cd ./developer-docs-site/static/examples/typescript && yarn first_transaction

      - uses: nick-fields/retry@v2
        name: first_nft
        with:
          max_attempts: 3
          timeout_minutes: 15
          command: cd ./developer-docs-site/static/examples/typescript && yarn first_nft

  # Note: We do not check first-coin yet.
  test-rust-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.GIT_SHA }}

      - uses: ./.github/actions/rust-setup

      - uses: nick-fields/retry@v2
        name: first-transaction
        with:
          max_attempts: 3
          timeout_minutes: 30
          command: cd ./developer-docs-site/static/examples/rust && cargo run -p first-transaction

  # Note: We do not check first_coin.py or hello_blockchain.py yet.
  test-python-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.GIT_SHA }}

      # This will use the version specified in .python-version in the root of the repo.
      - uses: actions/setup-python@v4
        id: install
        with:
          cache: 'pip'

      - run: cd ./developer-docs-site/static/examples/python && ${{ steps.install.outputs.python-path }} -m pip install -r requirements.txt

      - uses: nick-fields/retry@v2
        name: first-transaction
        with:
          max_attempts: 3
          timeout_minutes: 15
          command: cd ./developer-docs-site/static/examples/python && ${{ steps.install.outputs.python-path }} first_transaction.py

      - uses: nick-fields/retry@v2
        name: first-nft
        with:
          max_attempts: 3
          timeout_minutes: 15
          command: cd ./developer-docs-site/static/examples/python && ${{ steps.install.outputs.python-path }} first_nft.py
