name: Deploy community-platform to prod
on:
  push:
    branches:
      - main
    paths:
      - "ecosystem/platform/server/**"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    uses: ./.github/workflows/deploy-community-platform.yaml
    with:
      aptos_env: prod
    secrets: inherit
