name: Deploy community-platform to staging
on:
  push:
    branches:
      - main
    paths:
      - "ecosystem/platform/server/**"
  workflow_dispatch:
  # allow deployment to staging from pull request when special label is applied
  # TODO: create proper dev environment and only allow this for dev environment - reserve staging to reflect state of main branch.
  pull_request:
    types: [labeled, opened, synchronize, reopened]

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    if: |
      github.event_name == 'push' ||
      github.event_name == 'workflow_dispatch' ||
      contains(github.event.pull_request.labels.*.name, 'CICD:deploy-community-platform-to-staging')
    uses: ./.github/workflows/deploy-community-platform.yaml
    with:
      aptos_env: staging
    secrets: inherit
