name: Upload test results

inputs:
  BUILDPULSE_ACCESS_KEY_ID:
    required: true
  BUILDPULSE_SECRET_ACCESS_KEY:
    required: true
  DD_API_KEY:
    required: true
  SUITE:
    required: true

runs:
  using: composite
  steps:
    - name: Upload test results to BuildPulse for flaky test detection
      # Only run this step for branches where where we have access to secrets.
      # Run this step even when the tests fail. Skip if the workflow is cancelled.
      if: inputs.BUILDPULSE_SECRET_ACCESS_KEY != '' == 'true' && !cancelled()
      uses: Workshop64/buildpulse-action@main
      with:
        account: 99841612
        repository: 462597790
        path: target/nextest/ci/junit.xml
        key: ${{ inputs.BUILDPULSE_ACCESS_KEY_ID }}
        secret: ${{ inputs.BUILDPULSE_SECRET_ACCESS_KEY }}

    - uses: datadog/junit-upload-github-action@v1
      if: inputs.DD_API_KEY != '' && !cancelled()
      with:
        api-key: ${{ inputs.DD_API_KEY }}
        datadog-site: us5.datadoghq.com
        service: ${{ inputs.SUITE }}
        files: target/nextest/ci/junit.xml
