[package]
name = "aptos-telemetry-service"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
aptos-config = { path = "../../config" }
aptos-crypto = { path = "../../crates/aptos-crypto" }
aptos-crypto-derive = { path = "../../crates/aptos-crypto-derive" }
aptos-infallible = { path = "../../crates/aptos-infallible" }
aptos-logger = { path = "../../crates/aptos-logger" }
aptos-rest-client = { path = "../../crates/aptos-rest-client" }
aptos-types = { path = "../../types" }
bcs = "0.1.3"
chrono = "0.4"
clap = "3.1.8"
gcp-bigquery-client = "0.13"
hex = "0.4.3"
jsonwebtoken = "8.1"
rand = "0.7.3"
rand_core = { version = "0.5.1", default-features = false }
reqwest = { version = "0.11.10", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_repr = "0.1"
serde_with = "2.0"
serde_yaml = "0.8.24"
thiserror = "1.0"
tokio = { version = "1.18.2", features = ["full"] }
tokio_schedule = "0.3.0"
url = "2.2.2"
warp = { version = "0.3.2", features = ["tls"] }
